//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTranslate
{
    using System;
    using System.Collections.Generic;
    
    public partial class TJintuihuo
    {
        public TJintuihuo()
        {
            this.TJintuimingxi = new HashSet<TJintuimingxi>();
        }
    
        public int id { get; set; }
        public bool jintui { get; set; }
        public System.DateTime charushijian { get; set; }
    
        public virtual ICollection<TJintuimingxi> TJintuimingxi { get; set; }
    }
}
