//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTranslate
{
    using System;
    using System.Collections.Generic;
    
    public partial class TJintuimingxi
    {
        public TJintuimingxi()
        {
            this.TXiaoshou = new HashSet<TXiaoshou>();
        }
    
        public int id { get; set; }
        public int jinhuoid { get; set; }
        public long tiaoma { get; set; }
        public string kuanhao { get; set; }
        public string pinming { get; set; }
        public string yanse { get; set; }
        public string chima { get; set; }
        public decimal jinjia { get; set; }
        public decimal shoujia { get; set; }
        public short shuliang { get; set; }
        public System.DateTime jinhuoriqi { get; set; }
    
        public virtual TJintuihuo TJintuihuo { get; set; }
        public virtual ICollection<TXiaoshou> TXiaoshou { get; set; }
    }
}
