//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDXS.JCSJData {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JCSJData.IDataService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/BMZHLogin", ReplyAction="http://tempuri.org/IDataService/BMZHLoginResponse")]
        Tool.DB.JCSJ.TUser BMZHLogin(string dlm, string mm, string tzm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/BMZHLogin", ReplyAction="http://tempuri.org/IDataService/BMZHLoginResponse")]
        System.Threading.Tasks.Task<Tool.DB.JCSJ.TUser> BMZHLoginAsync(string dlm, string mm, string tzm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/CKZHLogin", ReplyAction="http://tempuri.org/IDataService/CKZHLoginResponse")]
        void CKZHLogin(int ckid, string tzm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/CKZHLogin", ReplyAction="http://tempuri.org/IDataService/CKZHLoginResponse")]
        System.Threading.Tasks.Task CKZHLoginAsync(int ckid, string tzm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/FDZHLogin", ReplyAction="http://tempuri.org/IDataService/FDZHLoginResponse")]
        void FDZHLogin(int fdid, string tzm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/FDZHLogin", ReplyAction="http://tempuri.org/IDataService/FDZHLoginResponse")]
        System.Threading.Tasks.Task FDZHLoginAsync(int fdid, string tzm);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/BMZHEditPsw", ReplyAction="http://tempuri.org/IDataService/BMZHEditPswResponse")]
        void BMZHEditPsw(string om, string nm);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/BMZHEditPsw", ReplyAction="http://tempuri.org/IDataService/BMZHEditPswResponse")]
        System.Threading.Tasks.Task BMZHEditPswAsync(string om, string nm);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/GetTiaomas", ReplyAction="http://tempuri.org/IDataService/GetTiaomasResponse")]
        Tool.DB.JCSJ.TTiaoma[] GetTiaomas(int Userid, string Kuanhao, string Tiaoma, System.DateTime Start, System.DateTime End);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/GetTiaomas", ReplyAction="http://tempuri.org/IDataService/GetTiaomasResponse")]
        System.Threading.Tasks.Task<Tool.DB.JCSJ.TTiaoma[]> GetTiaomasAsync(int Userid, string Kuanhao, string Tiaoma, System.DateTime Start, System.DateTime End);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/GetGongyingshangsByUserId", ReplyAction="http://tempuri.org/IDataService/GetGongyingshangsByUserIdResponse")]
        Tool.DB.JCSJ.TGongyingshang[] GetGongyingshangsByUserId(int UserId);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/GetGongyingshangsByUserId", ReplyAction="http://tempuri.org/IDataService/GetGongyingshangsByUserIdResponse")]
        System.Threading.Tasks.Task<Tool.DB.JCSJ.TGongyingshang[]> GetGongyingshangsByUserIdAsync(int UserId);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/GetKuanhaosByUserId", ReplyAction="http://tempuri.org/IDataService/GetKuanhaosByUserIdResponse")]
        Tool.DB.JCSJ.TKuanhao[] GetKuanhaosByUserId(int UserId);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/GetKuanhaosByUserId", ReplyAction="http://tempuri.org/IDataService/GetKuanhaosByUserIdResponse")]
        System.Threading.Tasks.Task<Tool.DB.JCSJ.TKuanhao[]> GetKuanhaosByUserIdAsync(int UserId);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/InsertKuanhao", ReplyAction="http://tempuri.org/IDataService/InsertKuanhaoResponse")]
        Tool.DB.JCSJ.TKuanhao InsertKuanhao(Tool.DB.JCSJ.TKuanhao k);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/InsertKuanhao", ReplyAction="http://tempuri.org/IDataService/InsertKuanhaoResponse")]
        System.Threading.Tasks.Task<Tool.DB.JCSJ.TKuanhao> InsertKuanhaoAsync(Tool.DB.JCSJ.TKuanhao k);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/EditKuanhao", ReplyAction="http://tempuri.org/IDataService/EditKuanhaoResponse")]
        void EditKuanhao(Tool.DB.JCSJ.TKuanhao k);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/EditKuanhao", ReplyAction="http://tempuri.org/IDataService/EditKuanhaoResponse")]
        System.Threading.Tasks.Task EditKuanhaoAsync(Tool.DB.JCSJ.TKuanhao k);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/DeleteKuanhao", ReplyAction="http://tempuri.org/IDataService/DeleteKuanhaoResponse")]
        void DeleteKuanhao(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/DeleteKuanhao", ReplyAction="http://tempuri.org/IDataService/DeleteKuanhaoResponse")]
        System.Threading.Tasks.Task DeleteKuanhaoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/InsertGongyingshang", ReplyAction="http://tempuri.org/IDataService/InsertGongyingshangResponse")]
        Tool.DB.JCSJ.TGongyingshang InsertGongyingshang(Tool.DB.JCSJ.TGongyingshang g);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/InsertGongyingshang", ReplyAction="http://tempuri.org/IDataService/InsertGongyingshangResponse")]
        System.Threading.Tasks.Task<Tool.DB.JCSJ.TGongyingshang> InsertGongyingshangAsync(Tool.DB.JCSJ.TGongyingshang g);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/EditGongyingshang", ReplyAction="http://tempuri.org/IDataService/EditGongyingshangResponse")]
        void EditGongyingshang(Tool.DB.JCSJ.TGongyingshang g);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/EditGongyingshang", ReplyAction="http://tempuri.org/IDataService/EditGongyingshangResponse")]
        System.Threading.Tasks.Task EditGongyingshangAsync(Tool.DB.JCSJ.TGongyingshang g);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/DeleteGongyingshang", ReplyAction="http://tempuri.org/IDataService/DeleteGongyingshangResponse")]
        void DeleteGongyingshang(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/DeleteGongyingshang", ReplyAction="http://tempuri.org/IDataService/DeleteGongyingshangResponse")]
        System.Threading.Tasks.Task DeleteGongyingshangAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/GetKuanhaoByMc", ReplyAction="http://tempuri.org/IDataService/GetKuanhaoByMcResponse")]
        Tool.DB.JCSJ.TKuanhao GetKuanhaoByMc(string kh);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/GetKuanhaoByMc", ReplyAction="http://tempuri.org/IDataService/GetKuanhaoByMcResponse")]
        System.Threading.Tasks.Task<Tool.DB.JCSJ.TKuanhao> GetKuanhaoByMcAsync(string kh);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/GetTiaomasByKuanhaoMc", ReplyAction="http://tempuri.org/IDataService/GetTiaomasByKuanhaoMcResponse")]
        Tool.DB.JCSJ.TTiaoma[] GetTiaomasByKuanhaoMc(string kh);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/GetTiaomasByKuanhaoMc", ReplyAction="http://tempuri.org/IDataService/GetTiaomasByKuanhaoMcResponse")]
        System.Threading.Tasks.Task<Tool.DB.JCSJ.TTiaoma[]> GetTiaomasByKuanhaoMcAsync(string kh);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/CheckKuanhaosChongfu", ReplyAction="http://tempuri.org/IDataService/CheckKuanhaosChongfuResponse")]
        string[] CheckKuanhaosChongfu(string[] khs);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/CheckKuanhaosChongfu", ReplyAction="http://tempuri.org/IDataService/CheckKuanhaosChongfuResponse")]
        System.Threading.Tasks.Task<string[]> CheckKuanhaosChongfuAsync(string[] khs);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/CheckTiaomaChongfu", ReplyAction="http://tempuri.org/IDataService/CheckTiaomaChongfuResponse")]
        string[] CheckTiaomaChongfu(string[] tms);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/CheckTiaomaChongfu", ReplyAction="http://tempuri.org/IDataService/CheckTiaomaChongfuResponse")]
        System.Threading.Tasks.Task<string[]> CheckTiaomaChongfuAsync(string[] tms);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/SaveKuanhaos", ReplyAction="http://tempuri.org/IDataService/SaveKuanhaosResponse")]
        Tool.DB.JCSJ.TKuanhao[] SaveKuanhaos(Tool.DB.JCSJ.TKuanhao[] ks);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/SaveKuanhaos", ReplyAction="http://tempuri.org/IDataService/SaveKuanhaosResponse")]
        System.Threading.Tasks.Task<Tool.DB.JCSJ.TKuanhao[]> SaveKuanhaosAsync(Tool.DB.JCSJ.TKuanhao[] ks);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/SaveTiaomas", ReplyAction="http://tempuri.org/IDataService/SaveTiaomasResponse")]
        Tool.DB.JCSJ.TTiaoma[] SaveTiaomas(Tool.DB.JCSJ.TTiaoma[] ts);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/SaveTiaomas", ReplyAction="http://tempuri.org/IDataService/SaveTiaomasResponse")]
        System.Threading.Tasks.Task<Tool.DB.JCSJ.TTiaoma[]> SaveTiaomasAsync(Tool.DB.JCSJ.TTiaoma[] ts);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/EditTiaoma", ReplyAction="http://tempuri.org/IDataService/EditTiaomaResponse")]
        void EditTiaoma(Tool.DB.JCSJ.TTiaoma t);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/EditTiaoma", ReplyAction="http://tempuri.org/IDataService/EditTiaomaResponse")]
        System.Threading.Tasks.Task EditTiaomaAsync(Tool.DB.JCSJ.TTiaoma t);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/GetTiaomasByUpdTime", ReplyAction="http://tempuri.org/IDataService/GetTiaomasByUpdTimeResponse")]
        Tool.DB.JCSJ.TTiaoma[] GetTiaomasByUpdTime();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/GetTiaomasByUpdTime", ReplyAction="http://tempuri.org/IDataService/GetTiaomasByUpdTimeResponse")]
        System.Threading.Tasks.Task<Tool.DB.JCSJ.TTiaoma[]> GetTiaomasByUpdTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/GetTiaomasByTiaomahaos", ReplyAction="http://tempuri.org/IDataService/GetTiaomasByTiaomahaosResponse")]
        Tool.DB.JCSJ.TTiaoma[] GetTiaomasByTiaomahaos(string[] tmhs);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/GetTiaomasByTiaomahaos", ReplyAction="http://tempuri.org/IDataService/GetTiaomasByTiaomahaosResponse")]
        System.Threading.Tasks.Task<Tool.DB.JCSJ.TTiaoma[]> GetTiaomasByTiaomahaosAsync(string[] tmhs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : FDXS.JCSJData.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<FDXS.JCSJData.IDataService>, FDXS.JCSJData.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Tool.DB.JCSJ.TUser BMZHLogin(string dlm, string mm, string tzm) {
            return base.Channel.BMZHLogin(dlm, mm, tzm);
        }
        
        public System.Threading.Tasks.Task<Tool.DB.JCSJ.TUser> BMZHLoginAsync(string dlm, string mm, string tzm) {
            return base.Channel.BMZHLoginAsync(dlm, mm, tzm);
        }
        
        public void CKZHLogin(int ckid, string tzm) {
            base.Channel.CKZHLogin(ckid, tzm);
        }
        
        public System.Threading.Tasks.Task CKZHLoginAsync(int ckid, string tzm) {
            return base.Channel.CKZHLoginAsync(ckid, tzm);
        }
        
        public void FDZHLogin(int fdid, string tzm) {
            base.Channel.FDZHLogin(fdid, tzm);
        }
        
        public System.Threading.Tasks.Task FDZHLoginAsync(int fdid, string tzm) {
            return base.Channel.FDZHLoginAsync(fdid, tzm);
        }
        
        public void BMZHEditPsw(string om, string nm) {
            base.Channel.BMZHEditPsw(om, nm);
        }
        
        public System.Threading.Tasks.Task BMZHEditPswAsync(string om, string nm) {
            return base.Channel.BMZHEditPswAsync(om, nm);
        }
        
        public Tool.DB.JCSJ.TTiaoma[] GetTiaomas(int Userid, string Kuanhao, string Tiaoma, System.DateTime Start, System.DateTime End) {
            return base.Channel.GetTiaomas(Userid, Kuanhao, Tiaoma, Start, End);
        }
        
        public System.Threading.Tasks.Task<Tool.DB.JCSJ.TTiaoma[]> GetTiaomasAsync(int Userid, string Kuanhao, string Tiaoma, System.DateTime Start, System.DateTime End) {
            return base.Channel.GetTiaomasAsync(Userid, Kuanhao, Tiaoma, Start, End);
        }
        
        public Tool.DB.JCSJ.TGongyingshang[] GetGongyingshangsByUserId(int UserId) {
            return base.Channel.GetGongyingshangsByUserId(UserId);
        }
        
        public System.Threading.Tasks.Task<Tool.DB.JCSJ.TGongyingshang[]> GetGongyingshangsByUserIdAsync(int UserId) {
            return base.Channel.GetGongyingshangsByUserIdAsync(UserId);
        }
        
        public Tool.DB.JCSJ.TKuanhao[] GetKuanhaosByUserId(int UserId) {
            return base.Channel.GetKuanhaosByUserId(UserId);
        }
        
        public System.Threading.Tasks.Task<Tool.DB.JCSJ.TKuanhao[]> GetKuanhaosByUserIdAsync(int UserId) {
            return base.Channel.GetKuanhaosByUserIdAsync(UserId);
        }
        
        public Tool.DB.JCSJ.TKuanhao InsertKuanhao(Tool.DB.JCSJ.TKuanhao k) {
            return base.Channel.InsertKuanhao(k);
        }
        
        public System.Threading.Tasks.Task<Tool.DB.JCSJ.TKuanhao> InsertKuanhaoAsync(Tool.DB.JCSJ.TKuanhao k) {
            return base.Channel.InsertKuanhaoAsync(k);
        }
        
        public void EditKuanhao(Tool.DB.JCSJ.TKuanhao k) {
            base.Channel.EditKuanhao(k);
        }
        
        public System.Threading.Tasks.Task EditKuanhaoAsync(Tool.DB.JCSJ.TKuanhao k) {
            return base.Channel.EditKuanhaoAsync(k);
        }
        
        public void DeleteKuanhao(int id) {
            base.Channel.DeleteKuanhao(id);
        }
        
        public System.Threading.Tasks.Task DeleteKuanhaoAsync(int id) {
            return base.Channel.DeleteKuanhaoAsync(id);
        }
        
        public Tool.DB.JCSJ.TGongyingshang InsertGongyingshang(Tool.DB.JCSJ.TGongyingshang g) {
            return base.Channel.InsertGongyingshang(g);
        }
        
        public System.Threading.Tasks.Task<Tool.DB.JCSJ.TGongyingshang> InsertGongyingshangAsync(Tool.DB.JCSJ.TGongyingshang g) {
            return base.Channel.InsertGongyingshangAsync(g);
        }
        
        public void EditGongyingshang(Tool.DB.JCSJ.TGongyingshang g) {
            base.Channel.EditGongyingshang(g);
        }
        
        public System.Threading.Tasks.Task EditGongyingshangAsync(Tool.DB.JCSJ.TGongyingshang g) {
            return base.Channel.EditGongyingshangAsync(g);
        }
        
        public void DeleteGongyingshang(int id) {
            base.Channel.DeleteGongyingshang(id);
        }
        
        public System.Threading.Tasks.Task DeleteGongyingshangAsync(int id) {
            return base.Channel.DeleteGongyingshangAsync(id);
        }
        
        public Tool.DB.JCSJ.TKuanhao GetKuanhaoByMc(string kh) {
            return base.Channel.GetKuanhaoByMc(kh);
        }
        
        public System.Threading.Tasks.Task<Tool.DB.JCSJ.TKuanhao> GetKuanhaoByMcAsync(string kh) {
            return base.Channel.GetKuanhaoByMcAsync(kh);
        }
        
        public Tool.DB.JCSJ.TTiaoma[] GetTiaomasByKuanhaoMc(string kh) {
            return base.Channel.GetTiaomasByKuanhaoMc(kh);
        }
        
        public System.Threading.Tasks.Task<Tool.DB.JCSJ.TTiaoma[]> GetTiaomasByKuanhaoMcAsync(string kh) {
            return base.Channel.GetTiaomasByKuanhaoMcAsync(kh);
        }
        
        public string[] CheckKuanhaosChongfu(string[] khs) {
            return base.Channel.CheckKuanhaosChongfu(khs);
        }
        
        public System.Threading.Tasks.Task<string[]> CheckKuanhaosChongfuAsync(string[] khs) {
            return base.Channel.CheckKuanhaosChongfuAsync(khs);
        }
        
        public string[] CheckTiaomaChongfu(string[] tms) {
            return base.Channel.CheckTiaomaChongfu(tms);
        }
        
        public System.Threading.Tasks.Task<string[]> CheckTiaomaChongfuAsync(string[] tms) {
            return base.Channel.CheckTiaomaChongfuAsync(tms);
        }
        
        public Tool.DB.JCSJ.TKuanhao[] SaveKuanhaos(Tool.DB.JCSJ.TKuanhao[] ks) {
            return base.Channel.SaveKuanhaos(ks);
        }
        
        public System.Threading.Tasks.Task<Tool.DB.JCSJ.TKuanhao[]> SaveKuanhaosAsync(Tool.DB.JCSJ.TKuanhao[] ks) {
            return base.Channel.SaveKuanhaosAsync(ks);
        }
        
        public Tool.DB.JCSJ.TTiaoma[] SaveTiaomas(Tool.DB.JCSJ.TTiaoma[] ts) {
            return base.Channel.SaveTiaomas(ts);
        }
        
        public System.Threading.Tasks.Task<Tool.DB.JCSJ.TTiaoma[]> SaveTiaomasAsync(Tool.DB.JCSJ.TTiaoma[] ts) {
            return base.Channel.SaveTiaomasAsync(ts);
        }
        
        public void EditTiaoma(Tool.DB.JCSJ.TTiaoma t) {
            base.Channel.EditTiaoma(t);
        }
        
        public System.Threading.Tasks.Task EditTiaomaAsync(Tool.DB.JCSJ.TTiaoma t) {
            return base.Channel.EditTiaomaAsync(t);
        }
        
        public Tool.DB.JCSJ.TTiaoma[] GetTiaomasByUpdTime() {
            return base.Channel.GetTiaomasByUpdTime();
        }
        
        public System.Threading.Tasks.Task<Tool.DB.JCSJ.TTiaoma[]> GetTiaomasByUpdTimeAsync() {
            return base.Channel.GetTiaomasByUpdTimeAsync();
        }
        
        public Tool.DB.JCSJ.TTiaoma[] GetTiaomasByTiaomahaos(string[] tmhs) {
            return base.Channel.GetTiaomasByTiaomahaos(tmhs);
        }
        
        public System.Threading.Tasks.Task<Tool.DB.JCSJ.TTiaoma[]> GetTiaomasByTiaomahaosAsync(string[] tmhs) {
            return base.Channel.GetTiaomasByTiaomahaosAsync(tmhs);
        }
    }
}
