//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.DB.FDXS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUser
    {
        public TUser()
        {
            this.TJinchuhuo = new HashSet<TJinchuhuo>();
            this.TKucunXZ = new HashSet<TKucunXZ>();
            this.TXiaoshou = new HashSet<TXiaoshou>();
        }
    
        public int id { get; set; }
        public string dengluming { get; set; }
        public string mima { get; set; }
        public string yonghuming { get; set; }
        public byte juese { get; set; }
        public string beizhu { get; set; }
        public byte zhuangtai { get; set; }
        public System.DateTime charushijian { get; set; }
        public System.DateTime xiuggaishijian { get; set; }
    
        public virtual ICollection<TJinchuhuo> TJinchuhuo { get; set; }
        public virtual ICollection<TKucunXZ> TKucunXZ { get; set; }
        public virtual ICollection<TXiaoshou> TXiaoshou { get; set; }
    }
}
