CREATE TABLE [dbo].[TFendian] (
    [id]            INT            IDENTITY (1, 1) NOT NULL,
    [fzxingbie]     TINYINT        NOT NULL,
    [fzleixing]     TINYINT        NOT NULL,
    [dianming]      NVARCHAR (10)  NOT NULL,
    [mianji]        SMALLINT       NOT NULL,
    [keliuliang]    SMALLINT       NOT NULL,
    [dangci]        TINYINT        NOT NULL,
    [dpxingzhi]     TINYINT        NOT NULL,
    [zhanrangfei]   DECIMAL (8, 2) NOT NULL,
    [yuezu]         DECIMAL (8, 2) NOT NULL,
    [dizhi]         NVARCHAR (50)  NOT NULL,
    [lianxiren]     NVARCHAR (5)   NOT NULL,
    [dianhua]       VARCHAR (11)   NOT NULL,
    [kaidianriqi]   DATE           NOT NULL,
    [zhuangtai]     TINYINT        NOT NULL,
    [beizhu]        NVARCHAR (50)  NOT NULL,
    [caozuorenid]   INT            NOT NULL,
    [charushijian]  DATETIME       NOT NULL,
    [xiugaishijian] DATETIME       NOT NULL,
    CONSTRAINT [PK_TFendian] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_TFendian_TUser] FOREIGN KEY ([caozuorenid]) REFERENCES [dbo].[TUser] ([id]),
    CONSTRAINT [IX_TFendian] UNIQUE NONCLUSTERED ([dianming] ASC)
);

