<?xml version="1.0" encoding="utf-8"?><Database Name="JCSJ" Class="JCSJDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CAI-DELL-17R;Initial Catalog=JCSJ;Integrated Security=True" SettingsObjectName="Tool.Properties.Settings" SettingsPropertyName="JCSJConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TUser" Member="TUser">
    <Type Name="TUser">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dengluming" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="mima" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="yonghuming" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="juese" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="beizhu" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="zhuangtai" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="charushijian" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="xiugaishijian" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="TUser_TTiaoma" Member="TTiaoma" ThisKey="id" OtherKey="caozuorenid" Type="TTiaoma" />
      <Association Name="TUser_TKuanhao" Member="TKuanhao" ThisKey="id" OtherKey="caozuorenid" Type="TKuanhao" />
      <Association Name="TUser_TGongyingshang" Member="TGongyingshang" ThisKey="id" OtherKey="caozuorenid" Type="TGongyingshang" />
    </Type>
  </Table>
  <Table Name="dbo.TTiaoma" Member="TTiaoma">
    <Type Name="TTiaoma">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tiaoma" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="yanse" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="chima" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="jinjia" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="shoujia" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="kuanhaoid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="gysid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="gyskuanhao" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="maishou" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="caozuorenid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="charushijian" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="xiugaishijian" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="TUser_TTiaoma" Member="TUser" ThisKey="caozuorenid" OtherKey="id" Type="TUser" IsForeignKey="true" />
      <Association Name="TKuanhao_TTiaoma" Member="TKuanhao" ThisKey="kuanhaoid" OtherKey="id" Type="TKuanhao" IsForeignKey="true" />
      <Association Name="TGongyingshang_TTiaoma" Member="TGongyingshang" ThisKey="gysid" OtherKey="id" Type="TGongyingshang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TKuanhao" Member="TKuanhao">
    <Type Name="TKuanhao">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="kuanhao" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="leixing" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="pinming" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="beizhu" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="caozuorenid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="charushijian" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="xiugaishijian" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="TKuanhao_TTiaoma" Member="TTiaoma" ThisKey="id" OtherKey="kuanhaoid" Type="TTiaoma" />
      <Association Name="TUser_TKuanhao" Member="TUser" ThisKey="caozuorenid" OtherKey="id" Type="TUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TGongyingshang" Member="TGongyingshang">
    <Type Name="TGongyingshang">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mingcheng" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="lianxiren" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="dianhua" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="dizhi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="beizhu" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="caozuorenid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="charushijian" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="xiugaishijian" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="TGongyingshang_TTiaoma" Member="TTiaoma" ThisKey="id" OtherKey="gysid" Type="TTiaoma" />
      <Association Name="TUser_TGongyingshang" Member="TUser" ThisKey="caozuorenid" OtherKey="id" Type="TUser" IsForeignKey="true" />
    </Type>
  </Table>
</Database>