//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_CK
{
    using System;
    using System.Collections.Generic;
    
    public partial class TChuruku
    {
        public TChuruku()
        {
            this.TChurukuMX = new HashSet<TChurukuMX>();
        }
    
        public int id { get; set; }
        public byte fangxiang { get; set; }
        public byte laiyuanquxiang { get; set; }
        public string beizhu { get; set; }
        public int caozuorenid { get; set; }
        public System.DateTime charushijian { get; set; }
        public System.DateTime xiugaishijian { get; set; }
        public Nullable<System.DateTime> shangbaoshijian { get; set; }
    
        public virtual TUser TUser { get; set; }
        public virtual ICollection<TChurukuMX> TChurukuMX { get; set; }
    }
}
