//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIANMA.JCSJData {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JCSJData.IDataService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/BMZHLogin", ReplyAction="http://tempuri.org/IDataService/BMZHLoginResponse")]
        Tool.DB.JCSJ.TUser BMZHLogin(string dlm, string mm, string tzm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/BMZHLogin", ReplyAction="http://tempuri.org/IDataService/BMZHLoginResponse")]
        System.Threading.Tasks.Task<Tool.DB.JCSJ.TUser> BMZHLoginAsync(string dlm, string mm, string tzm);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/BMZHEditPsw", ReplyAction="http://tempuri.org/IDataService/BMZHEditPswResponse")]
        void BMZHEditPsw(string om, string nm);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IDataService/BMZHEditPsw", ReplyAction="http://tempuri.org/IDataService/BMZHEditPswResponse")]
        System.Threading.Tasks.Task BMZHEditPswAsync(string om, string nm);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : BIANMA.JCSJData.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<BIANMA.JCSJData.IDataService>, BIANMA.JCSJData.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Tool.DB.JCSJ.TUser BMZHLogin(string dlm, string mm, string tzm) {
            return base.Channel.BMZHLogin(dlm, mm, tzm);
        }
        
        public System.Threading.Tasks.Task<Tool.DB.JCSJ.TUser> BMZHLoginAsync(string dlm, string mm, string tzm) {
            return base.Channel.BMZHLoginAsync(dlm, mm, tzm);
        }
        
        public void BMZHEditPsw(string om, string nm) {
            base.Channel.BMZHEditPsw(om, nm);
        }
        
        public System.Threading.Tasks.Task BMZHEditPswAsync(string om, string nm) {
            return base.Channel.BMZHEditPswAsync(om, nm);
        }
    }
}
