//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCSJGL.WCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.IService_GL")]
    public interface IService_GL {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_GL/GetAllUsers", ReplyAction="http://tempuri.org/IService_GL/GetAllUsersResponse")]
        Tool.DB.JCSJ.TUser[] GetAllUsers(bool ExceptAdmin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_GL/GetAllUsers", ReplyAction="http://tempuri.org/IService_GL/GetAllUsersResponse")]
        System.Threading.Tasks.Task<Tool.DB.JCSJ.TUser[]> GetAllUsersAsync(bool ExceptAdmin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_GL/Login", ReplyAction="http://tempuri.org/IService_GL/LoginResponse")]
        Tool.DB.JCSJ.TUser Login(string dlm, string mm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService_GL/Login", ReplyAction="http://tempuri.org/IService_GL/LoginResponse")]
        System.Threading.Tasks.Task<Tool.DB.JCSJ.TUser> LoginAsync(string dlm, string mm);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService_GLChannel : JCSJGL.WCF.IService_GL, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service_GLClient : System.ServiceModel.ClientBase<JCSJGL.WCF.IService_GL>, JCSJGL.WCF.IService_GL {
        
        public Service_GLClient() {
        }
        
        public Service_GLClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service_GLClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_GLClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service_GLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Tool.DB.JCSJ.TUser[] GetAllUsers(bool ExceptAdmin) {
            return base.Channel.GetAllUsers(ExceptAdmin);
        }
        
        public System.Threading.Tasks.Task<Tool.DB.JCSJ.TUser[]> GetAllUsersAsync(bool ExceptAdmin) {
            return base.Channel.GetAllUsersAsync(ExceptAdmin);
        }
        
        public Tool.DB.JCSJ.TUser Login(string dlm, string mm) {
            return base.Channel.Login(dlm, mm);
        }
        
        public System.Threading.Tasks.Task<Tool.DB.JCSJ.TUser> LoginAsync(string dlm, string mm) {
            return base.Channel.LoginAsync(dlm, mm);
        }
    }
}
