//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_JCSJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCangkuJinchuhuo
    {
        public TCangkuJinchuhuo()
        {
            this.TCangkuJinchuhuoMX = new HashSet<TCangkuJinchuhuoMX>();
        }
    
        public int id { get; set; }
        public int cangkuid { get; set; }
        public int oid { get; set; }
        public byte fangxiang { get; set; }
        public byte laiyuanquxiang { get; set; }
        public string beizhu { get; set; }
        public System.DateTime fashengshijian { get; set; }
        public System.DateTime shangbaoshijian { get; set; }
    
        public virtual TCangku TCangku { get; set; }
        public virtual ICollection<TCangkuJinchuhuoMX> TCangkuJinchuhuoMX { get; set; }
    }
}
