//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_JCSJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFendian
    {
        public TFendian()
        {
            this.TFendianJinchuhuo = new HashSet<TFendianJinchuhuo>();
            this.THuiyuan = new HashSet<THuiyuan>();
            this.TUser_Fendian = new HashSet<TUser_Fendian>();
            this.TXiaoshou = new HashSet<TXiaoshou>();
            this.TFendianKucun = new HashSet<TFendianKucun>();
        }
    
        public int id { get; set; }
        public byte fzxingbie { get; set; }
        public byte fzleixing { get; set; }
        public string dianming { get; set; }
        public short mianji { get; set; }
        public short keliuliang { get; set; }
        public byte dangci { get; set; }
        public byte dpxingzhi { get; set; }
        public decimal zhuanrangfei { get; set; }
        public decimal yuezu { get; set; }
        public string dizhi { get; set; }
        public string lianxiren { get; set; }
        public string dianhua { get; set; }
        public System.DateTime kaidianriqi { get; set; }
        public byte zhuangtai { get; set; }
        public string beizhu { get; set; }
        public int caozuorenid { get; set; }
        public System.DateTime charushijian { get; set; }
        public System.DateTime xiugaishijian { get; set; }
    
        public virtual TUser TUser { get; set; }
        public virtual ICollection<TFendianJinchuhuo> TFendianJinchuhuo { get; set; }
        public virtual ICollection<THuiyuan> THuiyuan { get; set; }
        public virtual ICollection<TUser_Fendian> TUser_Fendian { get; set; }
        public virtual ICollection<TXiaoshou> TXiaoshou { get; set; }
        public virtual ICollection<TFendianKucun> TFendianKucun { get; set; }
    }
}
