//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_JCSJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTiaoma
    {
        public TTiaoma()
        {
            this.TCangkuJinchuhuoMX = new HashSet<TCangkuJinchuhuoMX>();
            this.TFendianJinchuhuoMX = new HashSet<TFendianJinchuhuoMX>();
            this.TXiaoshou = new HashSet<TXiaoshou>();
            this.TCangkuKucunMX = new HashSet<TCangkuKucunMX>();
            this.TFendianKucunMX = new HashSet<TFendianKucunMX>();
        }
    
        public int id { get; set; }
        public int kuanhaoid { get; set; }
        public string gyskuanhao { get; set; }
        public string tiaoma { get; set; }
        public string yanse { get; set; }
        public string chima { get; set; }
        public decimal jinjia { get; set; }
        public decimal shoujia { get; set; }
        public int caozuorenid { get; set; }
        public System.DateTime charushijian { get; set; }
        public System.DateTime xiugaishijian { get; set; }
    
        public virtual ICollection<TCangkuJinchuhuoMX> TCangkuJinchuhuoMX { get; set; }
        public virtual ICollection<TFendianJinchuhuoMX> TFendianJinchuhuoMX { get; set; }
        public virtual TKuanhao TKuanhao { get; set; }
        public virtual TUser TUser { get; set; }
        public virtual ICollection<TXiaoshou> TXiaoshou { get; set; }
        public virtual ICollection<TCangkuKucunMX> TCangkuKucunMX { get; set; }
        public virtual ICollection<TFendianKucunMX> TFendianKucunMX { get; set; }
    }
}
