//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_JCSJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUser_Cangku
    {
        public int id { get; set; }
        public int yonghuid { get; set; }
        public int cangkuid { get; set; }
    
        public virtual TCangku TCangku { get; set; }
        public virtual TUser TUser { get; set; }
    }
}
